apiVersion: v1
kind: Service
metadata:
  name: cd4pe-service
  namespace: cd4pe
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: "8000"
    port: 8000
    targetPort: 8000
    protocol: TCP
  - name: "7000"
    port: 7000
    targetPort: 7000
    protocol: TCP
  selector:
    app: cd4pe
  type: LoadBalancer
