apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cd4pe-deployment
  namespace: cd4pe
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cd4pe
    spec:
      containers:
      - name: cd4pe
        image: puppet/continuous-delivery-for-puppet-enterprise:latest
        ports:
        - containerPort: 7000
          hostPort: 7000
          protocol: TCP
        - containerPort: 8080
          hostPort: 8080
          protocol: TCP
        - containerPort: 8000
          hostPort: 8000
          protocol: TCP
        env:
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              key: DB_USER
              name: cd4pe-frontend-config
        - name: DB_PASS
          valueFrom:
            configMapKeyRef:
              key: DB_PASS
              name: cd4pe-frontend-config
        - name: DB_ENDPOINT
          valueFrom:
            configMapKeyRef:
              key: DB_ENDPOINT
              name: cd4pe-frontend-config
        - name: cd4pe_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: cd4pe-secret
              key: secretkey
