apiVersion: v1
kind: Service
metadata:
  name: pfi-service
  namespace: pfi
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: "8000"
    port: 8000
    targetPort: 8000
    protocol: TCP
  - name: "7000"
    port: 7000
    targetPort: 7000
    protocol: TCP
  selector:
    app: pfi
  type: LoadBalancer
