apiVersion: v1
data:
  DB_ENDPOINT: mysql://mysql-service:3306/cd4pe
  DB_PASS: p@ssW0rd!
  DB_USER: cd4pe
kind: ConfigMap
metadata:
  labels:
    app: cd4pe
  name: cd4pe-frontend-config
  namespace: cd4pe
